--including libraries and stuff
pcall(require, "luarocks.loader")
gears = require("gears")
awful = require("awful")
require("awful.autofocus")
wibox = require("wibox")
beautiful = require("beautiful")
naughty = require("naughty")
menubar = require("menubar")
hotkeys_popup = require("awful.hotkeys_popup")
require("awful.hotkeys_popup.keys")

--starting modules
require("modules/error_handling")
require("modules/definitions")
require("modules/bar")
require("modules/keys")
require("modules/rules")
require("modules/signals")
require("modules/utils")
